server:
  port: 8082

img:
  car:
    dir: /Users/anseongjin/workspace/papas/car/imgs
#    dir: /Users/ssiky/papaswatch/pascar/imgs

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/papascar
      driver-class-name: org.postgresql.Driver
      username: admin
      password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        jdbc:
          fetch_size: 100
  data:
    mongodb:
      uri: mongodb://admin:1234@localhost:27017/papascar?authSource=admin
    redis:
      url: redis://localhost:6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: papascar-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.papas
kafka:
  topic:
    new-car-event: new-car-event

api:
  user:
    nickname: http://localhost:8080/users/nickname/{userId}