kafka:
  topic:
    new-car-event: new-car-event
  group:
    caching-car: car-caching-group

spring:
  main:
    web-application-type: none
  data:
    redis:
      url: redis://localhost:6379
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/papascar
      driver-class-name: org.postgresql.Driver
      username: admin
      password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
        default_batch_fetch_size: 100
        jdbc:
          fetch_size: 100
  kafka:
    bootstrap-servers: localhost:9092

api:
  user:
    nickname: http://localhost:8080/users/nickname/{userId}