server:
  port: 8081
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/papascar
      driver-class-name: org.postgresql.Driver
      username: admin
      password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        jdbc:
          fetch_size: 100